import os
import markdown
from weasyprint import HTML
from jinja2 import Template
from datetime import datetime
from typing import Dict, List, Optional
from shared_memory import SharedStateMemory, AgentType, Message, TaskStatus


class ComparisonTemplate:
    @staticmethod
    def get_side_by_side_template() -> str:
        return """
# Automotive Comparison Report: {{ car1 }} vs {{ car2 }}

*Generated on: {{ date }}*

## Quick Overview

| Specification | {{ car1 }} | {{ car2 }} |
|--------------|------------|------------|
{% for spec in comparison_table %}
| {{ spec['name'] }} | {{ spec['car1_value'] }} | {{ spec['car2_value'] }} |
{% endfor %}

---

## Detailed Analysis

### {{ car1 }} - In Depth
{{ car1_details }}

#### Pros
{% for pro in car1_pros %}
- {{ pro }}
{% endfor %}

#### Cons
{% for con in car1_cons %}
- {{ con }}
{% endfor %}

---

### {{ car2 }} - In Depth
{{ car2_details }}

#### Pros
{% for pro in car2_pros %}
- {{ pro }}
{% endfor %}

#### Cons
{% for con in car2_cons %}
- {{ con }}
{% endfor %}

---

## Recommendation

{{ recommendation }}

## Sources
{% for source in sources %}
- {{ source }}
{% endfor %}

---

*Report generated by Automotive AI System*
"""

    @staticmethod
    def get_detailed_report_template() -> str:
        return """
# Detailed Vehicle Report: {{ car_model }}

*Generated on: {{ date }}*

## Specifications

| Specification | Value |
|--------------|-------|
{% for spec_name, spec_value in specifications.items() %}
| {{ spec_name }} | {{ spec_value }} |
{% endfor %}

## Pros
{% for pro in pros %}
- {{ pro }}
{% endfor %}

## Cons
{% for con in cons %}
- {{ con }}
{% endfor %}

## Summary
{{ summary }}

## Performance Analysis
{{ performance_analysis }}

## Value Assessment
{{ value_assessment }}

## Sources
{% for source in sources %}
- {{ source }}
{% endfor %}

---

*Report generated by Automotive AI System*
"""

    @staticmethod
    def get_comparison_matrix_template() -> str:
        return """
# Multi-Car Comparison Matrix

*Generated on: {{ date }}*

## Comparison Matrix

| Specification | {% for car in cars %}{{ car }} | {% endfor %}
|--------------|{% for car in cars %}---|{% endfor %}
{% for spec in specs_list %}
| {{ spec['name'] }} | {% for value in spec['values'] %}{{ value }} | {% endfor %}
{% endfor %}

---

## Performance Scores

### Score Breakdown
| Car | Performance | Efficiency | Value | Technology | Overall |
|-----|------------|------------|-------|------------|---------|
{% for car in scores_list %}
| {{ car['name'] }} | {{ car['performance'] }}/10 | {{ car['efficiency'] }}/10 | {{ car['value'] }}/10 | {{ car['tech'] }}/10 | {{ car['overall'] }}/10 |
{% endfor %}

---

## Winner by Category

{% for category in winners_list %}
- **{{ category['name'] }}**: {{ category['winner'] }} ({{ category['reason'] }})
{% endfor %}

---

## Final Recommendation
{{ final_recommendation }}

---

*Report generated by Automotive AI System*
"""


class WriterAgent:
    def __init__(self, output_dir="/app/reports"):
        self.templates = ComparisonTemplate()
        self.output_dir = output_dir
        os.makedirs(self.output_dir, exist_ok=True)

    def read_from_shared_memory(self, shared_memory_data: Dict) -> Dict:
        print("📖 Reading from shared memory...")
        research_data = shared_memory_data.get("research_data", {})
        timestamp = shared_memory_data.get("timestamp", datetime.now().isoformat())
        print(f"   Found {len(research_data)} cars in shared memory")
        return {
            "cars": research_data,
            "timestamp": timestamp,
            "total_cars": len(research_data)
        }

    def generate_markdown_comparison(self, car1_name: str, car2_name: str,
                                     car1_data: Dict, car2_data: Dict) -> str:
        comparison_table = []
        specs_to_compare = [
            ("Horsepower", "horsepower", "hp"),
            ("0-60 mph", "acceleration", "s"),
            ("Range", "range_miles", "miles"),
            ("Price", "price", "$"),
            ("Battery", "battery_capacity", "kWh"),
            ("Top Speed", "top_speed", "mph")
        ]

        for display_name, spec_key, unit in specs_to_compare:
            car1_specs = car1_data.get('specifications', {})
            car2_specs = car2_data.get('specifications', {})
            car1_value = car1_specs.get(spec_key)
            car2_value = car2_specs.get(spec_key)

            if car1_value and car2_value:
                if spec_key == 'price':
                    comparison_table.append({
                        "name": display_name,
                        "car1_value": f"${car1_value:,}",
                        "car2_value": f"${car2_value:,}"
                    })
                else:
                    comparison_table.append({
                        "name": display_name,
                        "car1_value": f"{car1_value} {unit}".strip(),
                        "car2_value": f"{car2_value} {unit}".strip()
                    })

        score1 = self._calculate_overall_score(car1_data.get('specifications', {}))
        score2 = self._calculate_overall_score(car2_data.get('specifications', {}))
        
        if score1 > score2:
            winner = car1_name
            diff = round(score1 - score2, 1)
            recommendation = f"Based on our comprehensive analysis, the **{car1_name}** edges out the {car2_name} with a score of {score1}/10 vs {score2}/10 (difference of {diff} points)."
        elif score2 > score1:
            winner = car2_name
            diff = round(score2 - score1, 1)
            recommendation = f"Based on our comprehensive analysis, the **{car2_name}** outperforms the {car1_name} with a score of {score2}/10 vs {score1}/10 (difference of {diff} points)."
        else:
            recommendation = f"Both vehicles are evenly matched with scores of {score1}/10. Your choice should depend on specific priorities."

        template_data = {
            "car1": car1_name,
            "car2": car2_name,
            "date": datetime.now().strftime("%B %d, %Y"),
            "comparison_table": comparison_table,
            "car1_details": car1_data.get('summary', 'No details available'),
            "car2_details": car2_data.get('summary', 'No details available'),
            "car1_pros": car1_data.get('pros', ["No pros listed"]),
            "car2_pros": car2_data.get('pros', ["No pros listed"]),
            "car1_cons": car1_data.get('cons', ["No cons listed"]),
            "car2_cons": car2_data.get('cons', ["No cons listed"]),
            "recommendation": recommendation,
            "sources": list(set(
                car1_data.get('sources', []) + car2_data.get('sources', [])
            )) or ["Automotive Research Database"]
        }

        template = Template(self.templates.get_side_by_side_template())
        return template.render(**template_data)

    def generate_single_car_report(self, car_name: str, car_data: Dict) -> str:
        specifications = car_data.get('specifications', {})
        formatted_specs = {}
        spec_display_names = {
            'brand': 'Brand',
            'model': 'Model',
            'horsepower': 'Horsepower (hp)',
            'acceleration': '0-60 mph (seconds)',
            'range_miles': 'Range (miles)',
            'price': 'Price ($)',
            'battery_capacity': 'Battery (kWh)',
            'top_speed': 'Top Speed (mph)',
            'drivetrain': 'Drivetrain'
        }

        for key, display_name in spec_display_names.items():
            if specifications.get(key):
                value = specifications[key]
                if key == 'price':
                    formatted_specs[display_name] = f"${value:,}"
                else:
                    formatted_specs[display_name] = value

        performance_analysis = self._generate_performance_analysis(specifications)
        value_assessment = self._generate_value_assessment(specifications)

        template_data = {
            "car_model": car_name,
            "date": datetime.now().strftime("%B %d, %Y"),
            "specifications": formatted_specs,
            "pros": car_data.get('pros', ["No pros listed"]),
            "cons": car_data.get('cons', ["No cons listed"]),
            "summary": car_data.get('summary', 'No summary available'),
            "performance_analysis": performance_analysis,
            "value_assessment": value_assessment,
            "sources": car_data.get('sources', ["Automotive Research Database"])
        }

        template = Template(self.templates.get_detailed_report_template())
        return template.render(**template_data)

    def generate_multi_car_comparison(self, cars_data: Dict[str, Dict]) -> str:
        cars_list = list(cars_data.keys())
        specs_list = []
        spec_names = [
            ("Horsepower (hp)", "horsepower"),
            ("0-60 mph (s)", "acceleration"),
            ("Range (miles)", "range_miles"),
            ("Price ($)", "price"),
            ("Battery (kWh)", "battery_capacity"),
            ("Top Speed (mph)", "top_speed")
        ]

        for display_name, spec_key in spec_names:
            spec_values = []
            for car_name in cars_list:
                car_data = cars_data[car_name]
                specs = car_data.get('specifications', {})
                value = specs.get(spec_key)
                if value:
                    if spec_key == 'price':
                        spec_values.append(f"${value:,}")
                    else:
                        spec_values.append(str(value))
                else:
                    spec_values.append("N/A")
            specs_list.append({"name": display_name, "values": spec_values})

        scores_list = []
        for car_name in cars_list:
            car_data = cars_data[car_name]
            specs = car_data.get('specifications', {})
            perf_score = self._calculate_performance_score(specs)
            eff_score = self._calculate_efficiency_score(specs)
            value_score = self._calculate_value_score(specs)
            tech_score = self._calculate_tech_score(specs)
            overall = round((perf_score + eff_score + value_score + tech_score) / 4, 1)
            scores_list.append({
                "name": car_name,
                "performance": perf_score,
                "efficiency": eff_score,
                "value": value_score,
                "tech": tech_score,
                "overall": overall
            })

        winners_list = self._determine_winners(cars_data)
        best_car = max(scores_list, key=lambda x: x['overall']) if scores_list else None
        final_recommendation = f"After detailed analysis, the **{best_car['name']}** emerges as the top choice with an overall score of {best_car['overall']}/10." if best_car else "Unable to generate recommendation."

        template_data = {
            "date": datetime.now().strftime("%B %d, %Y"),
            "cars": cars_list,
            "specs_list": specs_list,
            "scores_list": scores_list,
            "winners_list": winners_list,
            "final_recommendation": final_recommendation
        }

        template = Template(self.templates.get_comparison_matrix_template())
        return template.render(**template_data)

    def markdown_to_pdf(self, markdown_content: str, filename: str) -> str:
        try:
            html_content = markdown.markdown(
                markdown_content,
                extensions=['tables', 'fenced_code', 'nl2br']
            )
            styled_html = f"""
            <!DOCTYPE html>
            <html>
            <head>
                <meta charset="UTF-8">
                <style>
                    body {{
                        font-family: Arial, sans-serif;
                        margin: 40px;
                        line-height: 1.6;
                    }}
                    h1 {{ color: #2E4057; border-bottom: 2px solid #2E4057; }}
                    h2 {{ color: #336699; margin-top: 30px; }}
                    table {{
                        border-collapse: collapse;
                        width: 100%;
                        margin: 20px 0;
                    }}
                    th, td {{
                        border: 1px solid #ddd;
                        padding: 12px;
                        text-align: left;
                    }}
                    th {{ background-color: #f2f2f2; }}
                </style>
            </head>
            <body>
                {html_content}
            </body>
            </html>
            """
            pdf_path = os.path.join(self.output_dir, f"{filename}.pdf")
            HTML(string=styled_html).write_pdf(pdf_path)
            print(f"   ✅ PDF generated: {pdf_path}")
            return pdf_path
        except Exception as e:
            print(f"   PDF generation failed: {e}")
            md_path = os.path.join(self.output_dir, f"{filename}.md")
            with open(md_path, 'w', encoding='utf-8') as f:
                f.write(markdown_content)
            return md_path

    def save_markdown(self, content: str, filename: str) -> str:
        filepath = os.path.join(self.output_dir, f"{filename}.md")
        with open(filepath, 'w', encoding='utf-8') as f:
            f.write(content)
        print(f"   ✅ Markdown saved: {filepath}")
        return filepath

    def _calculate_performance_score(self, specs: Dict) -> float:
        score = 5.0
        if specs.get('horsepower'):
            hp = float(specs['horsepower'])
            if hp > 400: score += 3
            elif hp > 300: score += 2
            elif hp > 200: score += 1
        if specs.get('acceleration'):
            acc = float(specs['acceleration'])
            if acc < 4: score += 3
            elif acc < 5: score += 2
            elif acc < 6: score += 1
        return min(10.0, max(0.0, round(score, 1)))

    def _calculate_efficiency_score(self, specs: Dict) -> float:
        score = 5.0
        if specs.get('range_miles'):
            range_val = float(specs['range_miles'])
            if range_val > 350: score += 4
            elif range_val > 300: score += 3
            elif range_val > 250: score += 2
            elif range_val > 200: score += 1
        return min(10.0, max(0.0, round(score, 1)))

    def _calculate_value_score(self, specs: Dict) -> float:
        score = 5.0
        if specs.get('price') and specs.get('range_miles'):
            price = float(specs['price'])
            range_val = float(specs['range_miles'])
            value_ratio = range_val / (price / 1000)
            if value_ratio > 8: score += 4
            elif value_ratio > 7: score += 3
            elif value_ratio > 6: score += 2
            elif value_ratio > 5: score += 1
        return min(10.0, max(0.0, round(score, 1)))

    def _calculate_tech_score(self, specs: Dict) -> float:
        score = 5.0
        if specs.get('battery_capacity'):
            battery = float(specs['battery_capacity'])
            if battery > 90: score += 3
            elif battery > 75: score += 2
            elif battery > 60: score += 1
        if specs.get('drivetrain'):
            if 'AWD' in str(specs['drivetrain']) or 'Dual Motor' in str(specs['drivetrain']):
                score += 2
        return min(10.0, max(0.0, round(score, 1)))

    def _calculate_overall_score(self, specs: Dict) -> float:
        return round((
            self._calculate_performance_score(specs) +
            self._calculate_efficiency_score(specs) +
            self._calculate_value_score(specs) +
            self._calculate_tech_score(specs)
        ) / 4, 1)

    def _generate_performance_analysis(self, specs: Dict) -> str:
        analysis = []
        if specs.get('horsepower') and specs.get('acceleration'):
            hp = specs['horsepower']
            acc = specs['acceleration']
            if hp > 400 and acc < 4:
                analysis.append("This is a high-performance vehicle with exceptional acceleration.")
            elif hp > 300 and acc < 5:
                analysis.append("This vehicle offers strong performance for enthusiastic driving.")
            else:
                analysis.append("This vehicle offers adequate performance for daily driving.")
        if specs.get('range_miles'):
            range_val = specs['range_miles']
            if range_val > 350:
                analysis.append(f"With {range_val} miles of range, it's excellent for long-distance travel.")
            else:
                analysis.append(f"The {range_val}-mile range is suitable for daily commuting.")
        return " ".join(analysis) if analysis else "Performance analysis not available."

    def _generate_value_assessment(self, specs: Dict) -> str:
        if specs.get('price') and specs.get('range_miles'):
            price = specs['price']
            range_val = specs['range_miles']
            if range_val and price:
                value_ratio = range_val / (price / 1000)
                if value_ratio > 8:
                    return f"Exceptional value! {value_ratio:.1f} miles per $1000 spent."
                elif value_ratio > 7:
                    return f"Strong value with {value_ratio:.1f} miles per $1000."
                else:
                    return f"Premium positioning with {value_ratio:.1f} miles per $1000."
        return "Value assessment not available."

    def _determine_winners(self, cars_data: Dict) -> List[Dict]:
        winners_list = []
        categories = {
            "Performance": "horsepower",
            "Range": "range_miles",
            "Value": "price",
            "Acceleration": "acceleration"
        }
        for category, spec_key in categories.items():
            best_car = None
            best_value = None
            for car_name, car_data in cars_data.items():
                specs = car_data.get('specifications', {})
                value = specs.get(spec_key)
                if value is not None:
                    if spec_key == 'price':
                        if best_value is None or value < best_value:
                            best_value = value
                            best_car = car_name
                    else:
                        if best_value is None or value > best_value:
                            best_value = value
                            best_car = car_name
            if best_car:
                if spec_key == 'price':
                    reason = f"Best value with ${best_value:,}"
                elif spec_key == 'horsepower':
                    reason = f"Most powerful with {best_value} hp"
                elif spec_key == 'range_miles':
                    reason = f"Longest range at {best_value} miles"
                elif spec_key == 'acceleration':
                    reason = f"Quickest 0-60 mph at {best_value}s"
                else:
                    reason = f"Best in category with {best_value}"
                winners_list.append({"name": category, "winner": best_car, "reason": reason})
        return winners_list


class WriterModule:
    def __init__(self, output_dir="/app/reports"):
        self.writer = WriterAgent(output_dir)
        self.output_history = []

    def process_request(self, request: Dict, shared_memory: Dict) -> Dict:
        request_id = request.get("request_id", f"WRITE-{len(self.output_history)+1:03d}")
        task_type = request.get("type", "side_by_side")
        output_format = request.get("format", "markdown")
        cars = request.get("cars", [])

        print(f"\n📝 Processing write request {request_id}")
        print(f"   Task: {task_type} comparison for {cars}")

        memory_data = self.writer.read_from_shared_memory(shared_memory)
        cars_data = memory_data["cars"]
        filtered_data = {car: cars_data[car] for car in cars if car in cars_data}

        if not filtered_data:
            return {"status": "error", "request_id": request_id, "error": "No requested cars found in shared memory"}

        try:
            if task_type == "side_by_side" and len(filtered_data) == 2:
                cars_list = list(filtered_data.keys())
                content = self.writer.generate_markdown_comparison(
                    cars_list[0], cars_list[1],
                    filtered_data[cars_list[0]], filtered_data[cars_list[1]]
                )
                filename = f"comparison_{cars_list[0]}_vs_{cars_list[1]}".replace(" ", "_")
            elif task_type == "multi_car":
                content = self.writer.generate_multi_car_comparison(filtered_data)
                filename = f"multi_car_comparison_{'_'.join(filtered_data.keys())}".replace(" ", "_")
            elif task_type == "single_report" and len(filtered_data) == 1:
                car = list(filtered_data.keys())[0]
                content = self.writer.generate_single_car_report(car, filtered_data[car])
                filename = f"report_{car}".replace(" ", "_")
            else:
                return {"status": "error", "request_id": request_id, "error": f"Invalid task type or car count"}

            outputs = {}
            if output_format in ["markdown", "both"]:
                md_path = self.writer.save_markdown(content, filename)
                outputs["markdown"] = md_path
            if output_format in ["pdf", "both"]:
                pdf_path = self.writer.markdown_to_pdf(content, filename)
                outputs["pdf"] = pdf_path

            self.output_history.append({
                "request_id": request_id,
                "timestamp": datetime.now().isoformat(),
                "cars": cars,
                "type": task_type,
                "outputs": outputs
            })

            return {
                "status": "success",
                "request_id": request_id,
                "outputs": outputs,
                "message": f"Successfully generated {output_format} report",
                "preview": content[:500] + "..."
            }
        except Exception as e:
            return {"status": "error", "request_id": request_id, "error": str(e)}


class WriterAgentWrapper:
    def __init__(self, shared_memory: SharedStateMemory, writer_module=None):
        self.agent_type = AgentType.WRITER
        self.name = "Automotive Writer"
        self.shared_memory = shared_memory
        self.writer = writer_module or WriterModule()
        self.capabilities = ["generate_comparison", "create_report", "export_pdf"]
        self.status = "idle"
        print(f"✅ Writer Agent '{self.name}' initialized")

    def process_message(self, message: Message) -> Optional[Message]:
        self.status = "processing"
        content = message.content
        message_type = message.message_type

        if message_type == "writing_request":
            report_type = content.get("type", "side_by_side")
            cars = content.get("cars", [])
            output_format = content.get("format", "both")
            task_id = content.get("task_id")
            workflow_id = content.get("workflow_id")

            print(f"\n📝 WRITER: Generating {report_type} report for: {cars}")
            cars_data = {}
            for car in cars:
                car_data = self.shared_memory.get_latest_research(car)
                if car_data:
                    cars_data[car] = car_data
                    print(f"   Found data for {car} in shared memory")

            if not cars_data:
                error_msg = "No research data found for requested cars"
                return Message(
                    from_agent=self.agent_type,
                    to_agent=AgentType.SUPERVISOR,
                    message_type="error",
                    content={"error": error_msg, "task_id": task_id},
                    timestamp=datetime.now().isoformat(),
                    message_id=f"err_{abs(hash(error_msg)) % 1000000:06d}"
                )

            writer_request = {
                "request_id": task_id,
                "type": report_type,
                "cars": cars,
                "format": output_format
            }
            writer_shared_memory = {
                "research_data": cars_data,
                "timestamp": datetime.now().isoformat()
            }

            try:
                writer_response = self.writer.process_request(writer_request, writer_shared_memory)
                if writer_response and writer_response.get("status") == "success":
                    report_name = f"{'_'.join(cars)}_{report_type}"
                    report_id = self.shared_memory.store_report(
                        report_name,
                        writer_response.get("outputs", {}),
                        report_type
                    )
                    self.shared_memory.update_task(
                        task_id,
                        TaskStatus.COMPLETED,
                        output_data={"report_id": report_id, "outputs": writer_response.get("outputs")}
                    )
                    self.status = "idle"
                    return Message(
                        from_agent=self.agent_type,
                        to_agent=AgentType.SUPERVISOR,
                        message_type="writing_response",
                        content={
                            "task_id": task_id,
                            "workflow_id": workflow_id,
                            "status": "success",
                            "report_id": report_id,
                            "outputs": writer_response.get("outputs", {})
                        },
                        timestamp=datetime.now().isoformat(),
                        message_id=f"resp_{abs(hash(str(writer_response))) % 1000000:06d}"
                    )
            except Exception as e:
                error_msg = f"Writer error: {str(e)}"
                return Message(
                    from_agent=self.agent_type,
                    to_agent=AgentType.SUPERVISOR,
                    message_type="error",
                    content={"error": error_msg, "task_id": task_id},
                    timestamp=datetime.now().isoformat(),
                    message_id=f"err_{abs(hash(error_msg)) % 1000000:06d}"
                )

        self.status = "idle"
        return None